### ISSUE TITLE
Differences in text size

### ISSUE THREAD

**Issue by sorawee** [racket/plot#126]
When I run tests under https://github.com/racket/plot/tree/master/plot-test/plot/tests and force regeneration, the new images have very small text size compared to the old images, even though all tests passed.

With Racket 8.11.1 on Mac:

Newly generated `new-p3d-bsp-9`:
![new-p3d-bsp-9](https://github.com/racket/plot/assets/9099577/45a42c1c-6674-41bf-be5b-f8e18644dab5)

Original `p3d-bsp-9` (from https://github.com/racket/plot/tree/master/plot-test/plot/tests/test-data):
![p3d-bsp-9](https://github.com/racket/plot/assets/9099577/d44f4087-0df5-4d79-9b0d-81783c87d787)

**Comment by alex-hhh** [comment]
This is expected behavior, even if it is surprising:  default fonts, and font rendering, is different on different platforms.  Usually plot images are generated on a linux VM (Where the github action runs) or on my Windows machine.

The generated plot steps ignore font rendering, by faking character with and heights, so the resulting draw steps themselves are identical on different platforms.   The images themselves are only used (usually by me) as a quick visual check if a test fails, and I know not to look at the font size :-).

https://github.com/racket/plot/blob/2417c228b0ce4708c796b4cb0a22cc818932a605/plot-test/plot/tests/helpers.rkt#L23

**Comment by sorawee** [comment]
Got it!
