### ISSUE TITLE
plot catches break exceptions but it should let them through

### ISSUE THREAD

**Issue by rfindler** [racket/plot#97]
I think this program should raise a break exception:

```
#lang racket
(require plot)

(plot
 (function
  (λ (x)
    (break-thread
     (current-thread)))))
```

It is probably best to catch only `exn:break?` exceptions.

**Comment by alex-hhh** [comment]
I suspect this is related to https://groups.google.com/g/racket-users/c/7lTTgg3He28

The X plot bounds cannot be determined by calling the function anyway (only the Y bounds can), so plot can report the "could not determine bounds" error without having to evaluate the function.  This will work as you expect:

```racket
(plot
 (function
  (λ (x)
    (break-thread
     (current-thread))) -10 10))
```

## Some other thoughts

The sampler will catch `exn:fail?` exceptions on this line (there is another one for 3D plots):

https://github.com/racket/plot/blob/c4126001f2c609e36c3aa12f300e9c673ab1a806/plot-lib/plot/private/common/sample.rkt#L163

This was probably done so that functions which are undefined for some regions can still plotted:

```racket
;; This would raise contract errors for values below 0, since log produces complex numbers but "function" expects reals
(plot (function log -10 10))
;; This produces a division by zero error at 0
(plot (function (lambda (x) (/ 1 x)) -1 1))
;; this function is undefined between -1 and 1, using user error, but can still be plotted
(define (my-function x)
  (cond ((< x -1)
         x)
        ((> x 1)
         x)
        (#t
         (error "my function is undefined between -1 and 1"))))
(plot (function my-function -10 10))
```

**Comment by mfelleisen** [comment]
Yes. 
Ignoring error results from math-y functions here may have been a part of the very early design when we used gnu plot and created images from those. It is natural because that's how you want to plot partially mathematical functions (tan, /, etc.) 

This still leaves us with at least two options: 

- log exceptions so someone like the OP can be told "check the logs" 
- if all probed X axis values signal errors instead of producing Y axis values, signal an error.

**Comment by alex-hhh** [comment]
Hi @rfindler , I am not sure I understand this part:

> I'm saying that catching break exceptions is just a bug. 

The plot package does not catch the break exceptions.  

Your program does not cause a break because plot never calls the function, since it knows that the plot bounds cannot be determined without having to call the function.   Here is an example that does cause a user break:

```racket
(plot
 (function
  (λ (x)
    (break-thread
     (current-thread))) -10 10))
```

**Comment by rfindler** [comment]
Oh, I'm sorry! I misunderstood what was happening. Thanks for clearing this up.
